const assert=require('node:assert/strict'),fs=require('node:fs'),api=require('../assets/home.js');
const now=new Date('2026-10-10T14:00:00Z');
const base={url:'https://agenda.vivreanyons.fr/evenements/test/',title:'Test',kind:'event',start:'2026-10-10',end:'2026-10-10',startTime:'10:00',endTime:'12:00'};
assert.equal(api.select([base],now).length,0);
assert.equal(api.select([{...base,endTime:''}],now).length,1);
const film={...base,kind:'cinema',sessions:[{date:'2026-10-10',time:'12:00'},{date:'2026-10-10',time:'18:30'}]};
assert.equal(api.select([film],now)[0].startTime,'18:30');
assert.equal(api.select([film],new Date('2026-10-10T19:00:00Z')).length,0);
assert.deepEqual(api.weekend('2026-10-11'),['2026-10-10','2026-10-11']);
assert.equal(api.stamp(new Date('2026-10-10T23:30:00Z')).slice(0,10),'2026-10-11');
assert.equal(api.season('2026-12-01'),'winter');assert.equal(api.esc('<script>'),'&lt;script&gt;');
const page=fs.readFileSync('index.html','utf8');
assert(page.indexOf('data-nyons-lodging')<page.indexOf('<header>'));
assert(page.includes('https://www.lalezardierenyons.com/situation-contact'));assert(page.includes('https://wa.me/33632076124'));
assert.equal((page.match(/class="home-latest-card"/g)||[]).length,5);
assert(!page.includes('<p>Chargement…</p>'));assert(page.includes('data-nyons-weather'));
assert(page.includes('<h1>Vivre à Nyons, simplement.</h1>'));
assert(page.includes('<title>Vivre à Nyons : guide local, sorties et bonnes adresses</title>'));
assert(page.includes('href="https://www.vivreanyons.fr/"'));
assert(!page.includes('data-agenda>'));assert.equal((page.match(/data-nyons-lodging\b/g)||[]).length,1);
console.log('Homepage dates, events, banner, metadata and weather: OK');
